#!/usr/bin/env python3
"""Collect the `## Notes` of every item into one repo-internal rationale file.

`## Notes` is where the writer records why a threshold has the value it has,
what was considered and rejected, and when the item was last read against the
code. It is roughly 40% of the SRS by volume, and it is the half nobody can
reconstruct two years later.

It is deliberately NOT in the technical file (`_lib.strip_internal_sections`):
a reviewer reads what the device shall do, not the drafting history of the
sentence that says so. It stays here, in the repository, under version control,
next to the code it explains.

Writes `docs/generated/_rationale.md`. Regenerated by `build_docs.py`; never
edit it by hand — edit the item.

Stdlib only. Python 3.12+.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import INTERNAL_SECTIONS, load_items  # noqa: E402

ROOT = Path.cwd()
ITEMS_DIR = ROOT / "docs" / "items"
OUT_PATH = ROOT / "docs" / "generated" / "_rationale.md"

CATEGORIES = ("SRS", "SDS", "TC", "RSK", "THR", "USC", "URSK", "PRSK", "MAP")


def _section(body: str, header: str) -> str:
    """The `## header` section of `body`, to the next H2 or the end."""
    m = re.search(rf"^##\s+{re.escape(header)}\s*$", body, flags=re.MULTILINE)
    if not m:
        return ""
    nxt = re.search(r"^##\s+", body[m.end():], flags=re.MULTILINE)
    end = m.end() + nxt.start() if nxt else len(body)
    return body[m.end():end].strip()


def build() -> tuple[list[str], int, int]:
    lines = [
        "# Rationale — repo-internal",
        "",
        "The `## Notes` of every active item, collected. **Not part of the technical "
        "file**: the exporters drop these sections (`_lib.strip_internal_sections`), "
        "and this file is the place to read them.",
        "",
        "Generated by `tools/build_rationale.py`. Do not edit — edit the item.",
        "",
    ]
    n_items = n_words = 0
    for category in CATEGORIES:
        collected = [
            (item, notes)
            for item in load_items(category, ITEMS_DIR)
            if item.status != "Deprecated"
            for notes in [_section(item.body, INTERNAL_SECTIONS[0])]
            if notes
        ]
        if not collected:
            continue
        lines += [f"## {category} — {len(collected)} items", ""]
        for item, notes in collected:
            n_items += 1
            n_words += len(notes.split())
            lines += [f"### `{item.id}` — {item.title}", "", notes, ""]
    return lines, n_items, n_words


def main() -> int:
    if not ITEMS_DIR.is_dir():
        print(f"ERROR: {ITEMS_DIR} not found — run from the repo root.", file=sys.stderr)
        return 1
    lines, n_items, n_words = build()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"rationale: {n_words} words from {n_items} items → {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
